django_proj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # new
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studentHub.urls')),
    path('', include('django.contrib.auth.urls')),  # Include Django's authentication URLs

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

studentHub/urls.py
from django.urls import path
from .views import *
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('resource/<int:resource_id>/', views.resource_detail, name='resource-detail'),
    path('edit-resource/<int:resource_id>/', views.edit_resource, name='edit-resource'),
    path('delete-resource/<int:resource_id>/', views.delete_resource, name='delete-resource'),
    path('add_resource/', views.add_resource, name='add-resource'),
    path('register/', views.register, name='register'),
    path('login/', views.custom_login, name='login'),
    path('download/<str:download_link>/', DownloadResourceView.as_view(), name='download-resource'),
    path('edit-profile/', edit_profile, name='edit-profile'),
    path('like/<int:resource_id>/', like_resource, name='like-resource'),
    path('comment/<int:resource_id>/', add_comment, name='add-comment'),
    path('logout/', logout.as_view(next_page='home'), name='logout'),
    
    path('send_message/', send_message, name='send_message'),
    path('view_messages/', view_messages, name='view_messages'),
    path('my-uploads/', my_uploads, name='my-uploads'),


    path('moderator/delete/resource/<int:resource_id>/', ModeratorDeleteResource, name='moderator-delete-resource'),
    path('moderator/delete/all-comments/<int:resource_id>/', ModeratorDeleteAllComments, name='moderator-delete-comments'),
    path('moderator/delete/comment/<int:comment_id>/', ModeratorDeleteComment, name='moderator-delete-comment'),
    path('moderator/block/user/<int:resource_id>/', ModeratorBlockUser, name='moderator-block-user'),
    path('<str:query>/', views.home, name='home'),

]

studentHub/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Resource(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    file = models.FileField(upload_to='resources/')
    date_uploaded = models.DateTimeField(auto_now_add=True)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.CharField(max_length=1000)
    subject = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    school = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    year = models.IntegerField(default=0)
    downloads = models.IntegerField(default=0)
    downloadLink = models.CharField(max_length=1000, default='')
    likes = models.ManyToManyField(User, related_name='liked_resources')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('resource-detail', kwargs={'resource_id': self.id})
    
    def get_user_rating(self):
        user = self.request.user if hasattr(self, 'request') and hasattr(self.request, 'user') else None
        rating = self.rating_set.filter(rater=user).first()
        return rating.rating if rating else None  

class Comment(models.Model):
    content = models.CharField(max_length=1000)
    date_posted = models.DateTimeField(auto_now_add=True)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    poster = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content
    def get_absolute_url(self):
        return reverse('resource-detail', kwargs={'resource_id': self.resource.id})
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"From {self.sender.username} to {self.recipient.username} - {self.timestamp}" 
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=1000, default='')
    profile_pic = models.ImageField(upload_to='images/', blank=True, null=True)
    school = models.CharField(max_length=100, default='TekUp')
    birthday = models.DateField(default='2000-01-01')  
    email = models.CharField(max_length=1000, default='') 
    classroom = models.CharField(max_length=1000, default='')
    role = models.CharField(max_length=100, default='Student')
    blocked = models.BooleanField(default=False)

    
    def __str__(self):
        return self.user.first_name
    def get_absolute_url(self):
        return reverse('profile')

studentHub/forms.py
# studenthub/forms.py

from django import forms
from .models import *


class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = ['title', 'description', 'file', 'tags', 'subject', 'course', 'school', 'department', 'semester', 'year']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'school',  'birthday', 'email', 'classroom', 'first_name', 'last_name'] 
        

    # Add first_name, last_name, and email fields from User model
    
    first_name = forms.CharField(max_length=30, required=False, label='First Name')
    last_name = forms.CharField(max_length=30, required=False, label='Last Name')
    email = forms.EmailField(max_length=100, required=False, label='Email')
    profile_pic = forms.ImageField(required=False, label='Profile Picture')
    school = forms.CharField(max_length=100, required=False, label='School')
    birthday = forms.DateField(required=False, label='Birthday')
    classroom = forms.CharField(max_length=100, required=False, label='Classroom')
    bio = forms.CharField(max_length=1000, required=False, label='Bio')
    

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        user = self.instance.user

        
        self.fields['school'].required = False
        self.fields['birthday'].required = False
        self.fields['classroom'].required = False
        self.fields['profile_pic'].required = False
        self.fields['bio'].required = False
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        
        
    def save(self, commit=True):
        user = self.instance.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()

        return super(UserProfileForm, self).save(commit)
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

studentHub/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from .forms import MessageForm, ResourceForm
from django.contrib import messages
from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from .forms import UserProfileForm
from django.contrib.auth.views import LogoutView
from django.views.generic import DeleteView


def home(request):
    
    search_query = request.GET.get('search', '')
    if search_query:
        search_words = search_query.split()
        for word in search_words:
            resources = Resource.objects.filter(title__icontains=word)
    else:
        resources = Resource.objects.all()
        
    return render(request, 'studenthub/home.html', {'resources': resources, 'search_query': search_query})

@login_required
def profile(request):
    return render(request, 'studenthub/profile.html')

def resource_detail(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)
    return render(request, 'studenthub/resource-detail.html', {'resource': resource})

@login_required
def edit_resource(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)
    if request.method == 'POST':
        form = ResourceForm(request.POST, request.FILES, instance=resource)
        if form.is_valid():
            resource = form.save(commit=False)
            resource.uploader = request.user
            if 'file' in request.FILES:
                resource.file = request.FILES['file']
            
            random_link = get_random_string(length=20)
            resource.downloadLink = reverse('download-resource', kwargs={'download_link': random_link})
            resource.save()
            messages.success(request, 'Resource updated successfully!')
            return redirect('profile')
        else:
            messages.error(request, 'Error updating the resource. Please check the form.')
    else:
        form = ResourceForm(instance=resource)
    return render(request, 'studenthub/edit_resource.html', {'form': form, 'resource': resource})

def delete_resource(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)
    resource.delete()
    messages.success(request, 'Resource deleted successfully.')
    return redirect('profile')

@login_required
def like_resource(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)

    # Check if the user has already liked the resource
    if request.user in resource.likes.all():
        resource.likes.remove(request.user)
        messages.success(request, 'You unliked the resource.')
    else:
        resource.likes.add(request.user)
        messages.success(request, 'You liked the resource.')

    return redirect('resource-detail', resource_id=resource_id)

@login_required
def add_comment(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)

    if request.method == 'POST':
        content = request.POST.get('comment')
        Comment.objects.create(content=content, resource=resource, poster=request.user)
        messages.success(request, 'Comment added successfully.')

    return redirect('resource-detail', resource_id=resource_id)

@login_required
def edit_profile(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            pro = form.save(commit=False)
            if 'profile_pic' in request.FILES:
                pro.profile_pic = request.FILES['profile_pic']
            pro.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile')
        else:
            messages.error(request, 'Error updating the profile. Please check the form.')
            print(form.errors)
            return render(request, 'studenthub/profile.html', {'form': form})
    else:
        form = UserProfileForm(instance=profile)

    return render(request, 'studenthub/profile.html', {'form': form})

@login_required
def add_resource(request):
    if request.method == 'POST':
        form = ResourceForm(request.POST, request.FILES)
        if form.is_valid():
            resource = form.save(commit=False)
            resource.uploader = request.user
            resource.file = request.FILES['file']
            random_link = get_random_string(length=20)
            resource.downloadLink = reverse('download-resource', kwargs={'download_link': random_link})
            resource.save()
            messages.success(request, 'Resource added successfully!')
            return redirect('home')
        else:
            messages.error(request, 'Error adding the resource. Please check the form.')
    else:
        form = ResourceForm()

    return render(request, 'studenthub/add_resource.html', {'form': form})

class DownloadResourceView(View):
    def get(self, request, download_link):
        resource = get_object_or_404(Resource, downloadLink=f'/download/{download_link}/')
        file_path = resource.file.path
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/force-download')
            response['Content-Disposition'] = f'attachment; filename={resource.file.name}'
            return response

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid form submission. Please correct the errors below.')
    else:
        form = UserCreationForm()
    
    return render(request, 'studenthub/register.html', {'form': form})

def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            userChk = User.objects.get(username=username)
            if ( userChk is not None and hasattr(userChk, 'profile') and userChk.profile.blocked):
                return render(request, 'studenthub/blocked.html')
        except:
            return render(request, 'studenthub/login.html')

        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if ( user.is_staff) :
                return HttpResponseRedirect(reverse('admin:index'))
            else:                
                return redirect('home')
    return render(request, 'studenthub/login.html')

class logout(LogoutView):
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        redirect('home',{'search_query':''})

        return response



def ModeratorDeleteComment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('resource-detail', resource_id=comment.resource.id)

def ModeratorDeleteResource(request, resource_id):
    resource = get_object_or_404(Resource, id=resource_id)
    resource.delete()
    return redirect('home') 

def ModeratorDeleteAllComments(request, resource_id):
    resource = get_object_or_404(Resource, id=resource_id)
    resource.comment_set.all().delete()
    return redirect('resource-detail', resource_id=resource_id)

def ModeratorBlockUser(request, resource_id):
    user_id = get_object_or_404(Resource, id=resource_id).uploader.id
    user = get_object_or_404(User, id=user_id)
    profile = user.profile
    if profile.blocked:
        profile.blocked = False
    else:
        profile.blocked = True
    profile.save()
    return redirect('resource-detail', resource_id=resource_id)

@login_required
def send_meszsage(request, recipient_username):
    users = User.objects.all()  # Fetch all users
    context = {'users': users}
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            recipient = User.objects.get(username=recipient_username)

            # Create and save the message
            Message.objects.create(sender=request.user, recipient=recipient, content=content)

            return redirect('view_messages')  # Redirect to the view_messages page after sending the message
    else:
        form = MessageForm()

    context = {'form': form, 'recipient_username': recipient_username}
    return render(request, 'studenthub/send_message.html', context)
@login_required
def view_messages(request):
    received_messages = Message.objects.filter(recipient=request.user).order_by('-timestamp')
    sent_messages = Message.objects.filter(sender=request.user).order_by('-timestamp')
    # Ajoutez ici la logique pour afficher les messages dans le modèle de messagerie
    return render(request, 'studenthub/view_messages.html', {'received_messages': received_messages,'sent_messages': sent_messages})
def my_view(request):
    users = User.objects.all()  # Fetch all users
    context = {'users': users}
    return render(request, 'my_template.html', context)

def send_message(request):
    # If a recipient_username is provided, fetch the User object
    recipient = None


    # Handle POST request: sending a message
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            # Assuming the form saves the message to the database
            message = form.save(commit=False)

templates/studenthub/add_resource.html
<!-- templates/studenthub/add_resource.html -->

{% extends 'studenthub/base.html' %}

{% block title %}Add Resource{% endblock %}

{% block content %}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="card-title">Add Resource</h2>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}" class="form-label">Title</label>
                <input type="text" name="title" id="title" class="form-control" required autofocus>
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
                <input type="text" name="description" id="description" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.file.id_for_label }}" class="form-label">File</label>
                <input type="file" name="file" id="file" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.tags.id_for_label }}" class="form-label">Tags</label>
                <input type="text" name="tags" id="tags" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.subject.id_for_label }}" class="form-label">Subject</label>
                <input type="text" name="subject" id="subject" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.course.id_for_label }}" class="form-label">Course</label>
                <input type="text" name="course" id="course" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.school.id_for_label }}" class="form-label">School</label>
                <input type="text" name="school" id="school" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.department.id_for_label }}" class="form-label">Department</label>
                <input type="text" name="department" id="department" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.semester.id_for_label }}" class="form-label">Semester</label>
                <input type="text" name="semester" id="semester" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.year.id_for_label }}" class="form-label">Year</label>
                <input type="text" name="year" id="year" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Add Resource</button>
        </form>
    </div>
</div>

{% endblock %}

templates/studenthub/base.html
<!-- templates/studenthub/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}StudentHub - Tek-UP!{% endblock %}</title>
    <!-- Add your CSS styles, Bootstrap CDN link, and Font Awesome link here -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"> <!-- Font Awesome link -->
    {% block styles %}{% endblock %}
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light {% if user.is_authenticated and user.profile.role == 'MOD' %} bg-warning {% else %}  bg-light {% endif %}">
    <a class="navbar-brand" href="{% url 'home' %}">
        <i class="fas fa-graduation-cap"></i> StudentHub <!-- Graduation cap icon -->
    </a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">
                        <i class="fas fa-user"></i> Profile <!-- User icon -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add-resource' %}">
                        <i class="fas fa-plus"></i> Add Resource <!-- Plus icon -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my-uploads' %}">
                        <i class="fas fa-book"></i> My Uploads <!-- Book icon -->
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'send_message' %}" class="nav-link">
                        <i class="fas fa-envelope"></i> Send Message <!-- Envelope icon -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'view_messages' %}">
                        <i class="fas fa-inbox"></i> Inbox <!-- Inbox icon -->
                    </a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">
                        <i class="fas fa-sign-out-alt"></i> Logout <!-- Sign out icon -->
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">
                        <i class="fas fa-sign-in-alt"></i> Login <!-- Sign in icon -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">
                        <i class="fas fa-user-plus"></i> Register <!-- User plus icon -->
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Content -->
<div class="container mt-3">
    {% block content %}{% endblock %}
</div>

<!-- Bootstrap JS and any additional scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/studenthub/myuploads.html
<!-- gestion_blog/templates/gestion_blog/uploads.html -->

{% include 'studenthub/base.html' %}

{% block title %}
    <h2 class="mt-3">Your Uploads</h2>
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            {% for resource in user.resource_set.all %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ resource.title }}</h5>
                            <p class="card-text">{{ resource.description }}</p>
                            <p class="card-text">Likes: {{ resource.likes.count }}</p>
                            <p class="card-text">Subject: {{ resource.subject }}</p>
                            <p class="card-text">Course: {{ resource.course }}</p>
                            <a href="{% url 'resource-detail' resource.id %}" class="btn btn-info btn-sm">View Details</a>
                            <a href="{% url 'edit-resource' resource.id %}" class="btn btn-warning btn-sm">Edit</a>
                            <a href="{% url 'delete-resource' resource.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/studenthub/profile.html
{% extends 'studenthub/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="card mt-5">
    <div class="card-header">
        <h2>Welcome, {{ user.first_name }}!</h2>
    </div>
    <div class="card-body">

        {% if user.profile.profile_pic %}
            <img src="{{ user.profile.profile_pic.url }}" alt="Profile Picture" class="img-fluid rounded mb-3" style="max-width: 200px;">
        {% elif user.profile.profile_pic and not user.profile.profile_pic.url %}
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Windows_10_Default_Profile_Picture.svg/2048px-Windows_10_Default_Profile_Picture.svg.png" alt="Profile Picture" class="img-fluid rounded mb-3" style="max-width: 200px;">
        {% else %}
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Windows_10_Default_Profile_Picture.svg/2048px-Windows_10_Default_Profile_Picture.svg.png" alt="Profile Picture" class="img-fluid rounded mb-3" style="max-width: 200px;">
        {% endif %}
        <form method="post" action="{% url 'edit-profile' %}" class="mb-3"  enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="bio">Bio:</label>
                <textarea name="bio" id="bio" class="form-control" rows="3">{{ user.profile.bio }}</textarea>
            </div>
            <div class="form-group">
                <label for="first_name">First Name:</label>
                <input type="text" name="first_name" id="first_name" class="form-control" value="{{ user.first_name }}">
            </div>
            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" name="last_name" id="last_name" class="form-control" value="{{ user.last_name }}">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email" id="email" class="form-control" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="profile_pic">Profile Picture:</label>
                <input type="file" name="profile_pic" id="profile_pic" class="form-control-file">
            </div>
            <div class="form-group">
                <label for="birthday">Birthday:</label>
                <input type="date" name="birthday" id="birthday" class="form-control" value="{{ user.profile.birthday|date:'Y-m-d' }}">
            </div>
            <div class="form-group">
                <label for="school">School:</label>
                <input type="text" name="school" id="school" class="form-control" value="{{ user.profile.school }}">
            </div>
            <div class="form-group">
                <label for="classroom">Classroom:</label>
                <input type="text" name="classroom" id="classroom" class="form-control" value="{{ user.profile.classroom }}">
            </div>

            <button type="submit" class="btn btn-primary">Update Profile</button>
        </form>

        <h2>Your Uploads</h2>
        <div class="row mt-3">
            {% for resource in user.resource_set.all %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ resource.title }}</h5>
                            <p class="card-text">{{ resource.description }}</p>
                            <p class="card-text">Likes: {{ resource.likes.count }}</p>
                            <p class="card-text">Subject: {{ resource.subject }}</p>
                            <p class="card-text">Course: {{ resource.course }}</p>
                            <a href="{% url 'resource-detail' resource.id %}" class="btn btn-info btn-sm">View Details</a>
                            <a href="{% url 'edit-resource' resource.id %}" class="btn btn-warning btn-sm">Edit</a>
                            <a href="{% url 'delete-resource' resource.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/studenthub/register.html
<!-- templates/studenthub/register.html -->

{% extends 'studenthub/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

<div class="card mt-5">
    <div class="card-header">
        <h2>Register</h2>
    </div>
    <div class="card-body">
        <form method="post" class="form-signup">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

{% endblock %}

templates/studenthub/send_message.html
<!-- gestion_blog/templates/gestion_blog/send_message.html -->

{% include 'studenthub/base.html' %}

{% block title %}
    <h2 class="mt-3"><i class="fas fa-envelope"></i> Send Message to {{ recipient.username }}</h2>
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-6">
                <form method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_content"><i class="fas fa-comment"></i> Message:</label>
                        {{ form.content }}
                    </div>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-paper-plane"></i> Send</button>
                </form>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-6">
                <p><i class="fas fa-user-plus"></i> Choose recipient:</p>
                <form method="get" action="{% url 'send_message' %}">
                    <div class="form-group">
                        <select name="username" id="id_username" class="form-control">
                            {% for user in users %}
                                <option value="{{ user.username }}">{{ user.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-secondary"><i class="fas fa-check"></i> Select</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}